(cl:in-package my_project_test-msg)
(cl:export '(DRIVEMODE_B-VAL
          DRIVEMODE_B
          THROTTLE-VAL
          THROTTLE
          ELECTRONIC_BREAK-VAL
          ELECTRONIC_BREAK
          HYDRAULIC_BREAK-VAL
          HYDRAULIC_BREAK
          STEERANGLE-VAL
          STEERANGLE
          PARK_B-VAL
          PARK_B
          LOADBRAKE_B-VAL
          LOADBRAKE_B
          GEAR-VAL
          GEAR
          DUMP_BED-VAL
          DUMP_BED
          POWERSUPPLY_B-VAL
          POWERSUPPLY_B
          ENGINE_B-VAL
          ENGINE_B
          TURTLE_B-VAL
          TURTLE_B
          LUBRICATE_B-VAL
          LUBRICATE_B
          FIREPREVENT_B-VAL
          FIREPREVENT_B
          EMERGENCYBRAKE_B-VAL
          EMERGENCYBRAKE_B
          LIGHTING_B-VAL
          LIGHTING_B
          HORN_B-VAL
          HORN_B
          LEFTLAMP_B-VAL
          LEFTLAMP_B
          RIGHTLAMP_B-VAL
          RIGHTLAMP_B
          BOTHLAMP_B-VAL
          BOTHLAMP_B
))