(cl:in-package my_project_test-msg)
(cl:export '(HEADER-VAL
          HEADER
          OEMSTATEFLAG-VAL
          OEMSTATEFLAG
          CTRL_CMDS_TO_LIGHTS_OF_OEM_VEHICLE-VAL
          CTRL_CMDS_TO_LIGHTS_OF_OEM_VEHICLE
          SAFE_CTRL_POWER_CMDS_TO_OEM_VEHICLE-VAL
          SAFE_CTRL_POWER_CMDS_TO_OEM_VEHICLE
          THROTTLECMD-VAL
          THROTTLECMD
          BREAKCMD-VAL
          BREAKCMD
          GEARCMD-VAL
          GEARCMD
          STEERANGLE-VAL
          STEERANGLE
          RETARDER_CMD-VAL
          RETARDER_CMD
          PARKBREAK-VAL
          PARKBREAK
          HORN-VAL
          HORN
          LOW_BEAMS-VAL
          LOW_BEAMS
          HIGH_BEAMS-VAL
          HIGH_BEAMS
          TURN_INDICATORS-VAL
          TURN_INDICATORS
          MARKER_LIGHTS-VAL
          MARKER_LIGHTS
          HAZARD_LIGHTS-VAL
          HAZARD_LIGHTS
          DUMP_BED-VAL
          DUMP_BED
          AUTO_LUBE-VAL
          AUTO_LUBE
          REST-VAL
          REST
          LOAD_BREAK-VAL
          LOAD_BREAK
))