(cl:in-package my_project_test-msg)
(cl:export '(DRIVERMODE_B-VAL
          DRIVERMODE_B
          GEARP_B-VAL
          GEARP_B
          LOADBRAKE_B-VAL
          LOADBRAKE_B
          TURTLE_B-VAL
          TURTLE_B
          TAKEOVER_B-VAL
          TAKEOVER_B
          GEAR-VAL
          GEAR
          WHEELANGLE-VAL
          WHEELANGLE
          VELOCITY-VAL
          VELOCITY
          RPM-VAL
          RPM
          THROTTLE-VAL
          THROTTLE
          ELECTRONIC_BREAK-VAL
          ELECTRONIC_BREAK
          VECHLEID-VAL
          VECHLEID
          ENGINESPEED-VAL
          ENGINESPEED
          BATTERYVOLTAGE-VAL
          BATTERYVOLTAGE
          FAULTTOTAL-VAL
          FAULTTOTAL
          DUMP_BED-VAL
          DUMP_BED
          LOADING-VAL
          LOADING
          FAULTCODE-VAL
          FAULTCODE
          ELECCONTROLTEMP-VAL
          ELECCONTROLTEMP
          OIL-VAL
          OIL
          MILEAGE-VAL
          MILEAGE
          LIGHTING_B-VAL
          LIGHTING_B
          HORN_B-VAL
          HORN_B
          LEFTLAMP_B-VAL
          LEFTLAMP_B
          RIGHTLAMP_B-VAL
          RIGHTLAMP_B
          BOTHLAMP_B-VAL
          BOTHLAMP_B
))