# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from my_project_test/CmdFromControllerToCAN.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class CmdFromControllerToCAN(genpy.Message):
  _md5sum = "9a522b352bacc640b9b26f3ed3fdba69"
  _type = "my_project_test/CmdFromControllerToCAN"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """# [topic_name]:/pingshuo_controller_node/TruckCmdFromControllerToCAN

Header header

float64 accel_pedal_cmd			            #油门控制量 0~100
float64 retard_pedal_cmd		            #电缓行控制量 0~100
int16   gear_cmd				            #目标档位指令 0-N 1-D 2-R
float64 brake_pedal_cmd			            #液压工作制动控制量 0~100
int16   lift_container_cmd			        #0-保持 1-举升 2-降落 3-浮动
int16   load_brake_cmd			            #装载制动开关 0-不制动 1-制动
int16   park_brake_cmd                      #驻车制动开关 0-不制动 1-制动
float64 target_angle_of_control_wheel	    #左前轮控制轮转向角 -35~35 deg
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id
"""
  __slots__ = ['header','accel_pedal_cmd','retard_pedal_cmd','gear_cmd','brake_pedal_cmd','lift_container_cmd','load_brake_cmd','park_brake_cmd','target_angle_of_control_wheel']
  _slot_types = ['std_msgs/Header','float64','float64','int16','float64','int16','int16','int16','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,accel_pedal_cmd,retard_pedal_cmd,gear_cmd,brake_pedal_cmd,lift_container_cmd,load_brake_cmd,park_brake_cmd,target_angle_of_control_wheel

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(CmdFromControllerToCAN, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.accel_pedal_cmd is None:
        self.accel_pedal_cmd = 0.
      if self.retard_pedal_cmd is None:
        self.retard_pedal_cmd = 0.
      if self.gear_cmd is None:
        self.gear_cmd = 0
      if self.brake_pedal_cmd is None:
        self.brake_pedal_cmd = 0.
      if self.lift_container_cmd is None:
        self.lift_container_cmd = 0
      if self.load_brake_cmd is None:
        self.load_brake_cmd = 0
      if self.park_brake_cmd is None:
        self.park_brake_cmd = 0
      if self.target_angle_of_control_wheel is None:
        self.target_angle_of_control_wheel = 0.
    else:
      self.header = std_msgs.msg.Header()
      self.accel_pedal_cmd = 0.
      self.retard_pedal_cmd = 0.
      self.gear_cmd = 0
      self.brake_pedal_cmd = 0.
      self.lift_container_cmd = 0
      self.load_brake_cmd = 0
      self.park_brake_cmd = 0
      self.target_angle_of_control_wheel = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_2dhd3hd().pack(_x.accel_pedal_cmd, _x.retard_pedal_cmd, _x.gear_cmd, _x.brake_pedal_cmd, _x.lift_container_cmd, _x.load_brake_cmd, _x.park_brake_cmd, _x.target_angle_of_control_wheel))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 40
      (_x.accel_pedal_cmd, _x.retard_pedal_cmd, _x.gear_cmd, _x.brake_pedal_cmd, _x.lift_container_cmd, _x.load_brake_cmd, _x.park_brake_cmd, _x.target_angle_of_control_wheel,) = _get_struct_2dhd3hd().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_2dhd3hd().pack(_x.accel_pedal_cmd, _x.retard_pedal_cmd, _x.gear_cmd, _x.brake_pedal_cmd, _x.lift_container_cmd, _x.load_brake_cmd, _x.park_brake_cmd, _x.target_angle_of_control_wheel))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 40
      (_x.accel_pedal_cmd, _x.retard_pedal_cmd, _x.gear_cmd, _x.brake_pedal_cmd, _x.lift_container_cmd, _x.load_brake_cmd, _x.park_brake_cmd, _x.target_angle_of_control_wheel,) = _get_struct_2dhd3hd().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_2dhd3hd = None
def _get_struct_2dhd3hd():
    global _struct_2dhd3hd
    if _struct_2dhd3hd is None:
        _struct_2dhd3hd = struct.Struct("<2dhd3hd")
    return _struct_2dhd3hd
